### ISSUE TITLE
Indicate Which Python

### ISSUE THREAD

**Issue by flounders** [oohlaf/dotsecrets#3]
I had some issues with building this project due to it being Python 2 rather than Python 3. I had no idea until I searched for the missing dependency UserDict. This tripped me up because on Arch Linux the default Python is 3 instead of 2. It would be helpful to indicate this in the README or even to see what it will take to switch to 3.

**Comment by oohlaf** [comment]
UserDict got moved to a different location in Python3. I also changed some of the other incompatibilities. The test suite runs without error on Python3.6 now. Let me know if this works for you.

Fixed in 9c0c49ee1d9181e54d3058e88af7f11f65b8dd5d, 25121b9bdceda0b0a252e2bdec0e76a4eb733a4c, and a085ae3cd77d32426fcabfc02e9af1e66fceee81

**Comment by flounders** [comment]
That runs with the default interpreter. I'm having another issue which I will open separately.
